int a = 2;
int b = 10;
int c = 3;
int d = 1;
int e = 4;
int max = 0;
if (a > max) max = a;
if (b > max) max = b;
if (c > max) max = c;
if (d > max) max = d;
if (e > max) max = e;
Console.WriteLine(max);
